# This is a basic workflow to help you get started with Actions

name: dev-ci-cd

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '14.x'
          
      # Install project dependencies
      - name: Install dependencies
        run: cd functions && npm install
        
      # Build
      - name: Build
        run: cd functions && npm run build
      
          
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: GitHub Action for Firebase
          uses: w9jds/firebase-action@v2.0.0
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        - name: Use a firebase dev project
          run: firebase use --token "${{ secrets.FIREBASE_TOKEN }}" --project "expense-sheets-dev"
        - name: Set firebase configuration
          run: firebase functions:config:set expenseservice.environment=dev  --token "${{ secrets.FIREBASE_TOKEN }}" --project "expense-sheets-dev"
        - name: Deploy the build
          run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "expense-sheets-dev"
